export const title = {
  home: "Juha Mikael / Home",
  blog: "Juha Mikael / Blog",
  projects: "Juha Mikael / Projects",
  portfolio: "Juha Mikael / Portfolio",
  skills: "Juha Mikael / Skills",
  contact: "Juha Mikael / Contact",
};

export const description = {
  home: "Juha Mikael's personal website showcasing his skills, projects, and insights on web development and technology",
  blog: "Juha Mikael's blog, featuring articles on web development, technology trends, and personal insights.",
  projects:
    "A collection of Juha Mikael's diverse projects spanning web development, applications, and more.",
  portfolio:
    "Juha Mikael's curated portfolio, highlighting his best works and significant achievements in the tech industry",
  skills:
    "Explore Juha Mikael's expertise in web development, including languages, frameworks, and tools he excels in.",
  contact:
    "Reach out to Juha Mikael. Whether it's for collaboration, queries, or just to say hi, he'd love to hear from you.",
};

export const keywords = {
  home: [
    "Juha Mikael",
    "personal website",
    "home",
    "introduction",
    "about",
    "profile",
    "TypeScript",
    "JavaScript",
    "React",
    "Next.js",
    "Node.js",
    "Python",
    "Rust",
    "cloudflare",
    "C#",
    "FastAPI",
    "Express",
    "PostgreSQL",
    "Firebase",
    "MySQL",
    "SQLite",
    "Supabase",
    "Prisma",
    "Vercel",
    "Sanity",
  ],
  blog: [
    "Juha Mikael",
    "blog",
    "articles",
    "writing",
    "opinions",
    "thoughts",
    "cloudflare",
    "updates",
  ],
  projects: [
    "Juha Mikael",
    "projects",
    "portfolio",
    "work",
    "endeavors",
    "achievements",
    "showcase",
    "React",
    "Next.js",
    "Node.js",
    "Python",
    "Rust",
    "C#",
    "FastAPI",
    "Express",
    "PostgreSQL",
    "Firebase",
    "MySQL",
    "SQLite",
    "Supabase",
    "Prisma",
    "Vercel",
    "Sanity",
  ],
  portfolio: [
    "Juha Mikael",
    "portfolio",
    "showcase",
    "work samples",
    "best work",
    "featured projects",
    "visuals",
  ],
  skills: [
    "Juha Mikael",
    "skills",
    "abilities",
    "expertise",
    "talents",
    "capabilities",
    "proficiency",
  ],
  contact: [
    "Juha Mikael",
    "contact",
    "reach out",
    "connect",
    "get in touch",
    "email",
    "message",
    "inquiry",
  ],
};
