import "./globals.css";
import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import { ThemeProvider } from "@/components/theme-provider";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { cn } from "@/lib/utils";
const font = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Juha Mikael ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <html lang="en" className="dark" style={{ colorScheme: "dark" }}>
        <body className={cn("mx-10 md:mx-20 2xl:mx-96", font.className)}>
          <ThemeProvider attribute="class">
            <Navbar />
            <div className="min-h-screen">{children}</div>
            <Footer />
          </ThemeProvider>
        </body>
      </html>
    </>
  );
}
